Milestone components
HADDADSOHAIB/math-magiciens pull request #2
Opened 2020-06-01 22:53 UTC by HADDADSOHAIB

In this milestone, I added the skeleton components required to make a calculator. I added four component: Button, ButtonPanel, Display, and App.

2020-06-02 10:58 UTC, shloch requested changes
## Hello @HADDADSOHAIB , 

You did everything pretty correct. However for the sake of sticking with the guidelines, please you have some small debugging to do below prior to your last thumbs up

### Happy coding

2020-06-02 10:58 UTC, shloch commented on src/components/Display.js
> +};
`result` should be a string [ see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png) ]

2020-06-02 10:58 UTC, shloch commented on src/components/Display.js
> +
That means `defaultProps` value should be `"0"` [[requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)]

2020-06-02 11:04 UTC, HADDADSOHAIB commented
@shloch  thanks for the review, I fix it the issue :)

2020-06-03 00:06 UTC, fatymahmed approved these changes
## Hi @HADDADSOHAIB,
**Great job making the changes 🎉🎉**
## ✔️ Approved!

2020-06-05 15:43 UTC, merged